#
# file : Makefile
# date : jeudi 19 décembre 2019, 13:19:09 (UTC+0100)
# author : sedelpeuch
# description :
all: project

project:
	pdflatex learn_git.tex

# Build document.
run:
	evince rapport.pdf &

# Clean directory
clean:
	rm -f *~ *.o  *aux *.log *.out *.toc rapport.pdf

