language: c++

sudo: false

branches:
  only:
    - master

script:
  - make test
  - make code
  - make doc

compiler: gcc

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
