#
# file : Makefile
# date : jeudi 19 décembre 2019, 13:19:09 (UTC+0100)
# author : sedelpeuch
# description :
all:
	pdflatex dossier_presentation.tex

# Clean directory
clean:
	rm -f *~ *.o  *aux *.log *.out *.toc rapport.pdf

