#
# file : Makefile
# date : samedi 11 janvier 2020, 12:24:22 (UTC+0100)
# author : sedelpeuch
# description :
all: project

project:
	pdflatex description.tex

# Build document.
run:
	evince description.pdf &

# Clean directory
clean:
	rm -f *~ *.o  *aux *.log *.out *.toc rapport.pdf

