#
# file : Makefile
# date : jeudi 19 décembre 2019, 13:19:09 (UTC+0100)
# author : sedelpeuch
# description :
all: git

git:
	pdflatex learn_git.tex

makefile:
	pdflatex learn_makefile.tex

# Clean directory
clean:
	rm -f *~ *.o  *aux *.log *.out *.toc rapport.pdf

