name: Code check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Minimal_level:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd code/build/ && make project && ./bin/project
      
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: cd code/build/ && make test && ./bin/test
        
