name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make code
      
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
        
      - name: Coverage check
        uses: devmasx/coverage-check-action@v1.1.0
        with:
          # lcov | simplecov
          type: lcov # default is lcov
          # Github token for create checks
          token: World # default is World
          # Minimum coverage
          min_coverage: 80 # optional, default is 80
          # Json with coverage result
          result_path: coverage/example.lcov
