name: Code check

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'

jobs:
  Minimal_level:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: | 
        cd code 
        cd build
        cmake .. 
        make project
      
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: | 
          cd code 
          cd build
          cmake .. 
          cd ../../
          make test
      - uses: actions/checkout@v2
      - name: coverage
        run: |
          cd code 
          cd build
          cmake ..
          cd ../../
          make test
          sudo apt install lcov
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
          lcov --list coverage.info # debug info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"    
      
