name: Code check

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'

jobs:
  Minimal_level:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: | 
        cd code 
        cd build
        cmake .. 
        cd ../../
        make code
      
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: | 
          cd code 
          cd build
          cmake .. 
          cd ../../
          make test
