name: Code check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Minimal_level:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: | 
        cd code 
        mkdir build
        cd build
        cmake .. 
        cd ../../
        cp code/rasp/src/fichier_ecocup.txt code/build/
        make code
      
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: | 
          cd code 
          mkdir build
          cd build
          cmake .. 
          cd ../../
          cp code/rasp/src/fichier_ecocup.txt code/build/
          make test
        
