name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make code
      
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
    
      - uses: devmasx/coverage-check-action@v1.1.0
      - name: coverage
        with:
          type: lcov
          result_path: coverage/example.lcov
          min_coverage: 80
          token: world
