name: Code check

on:
  push:
    branches: [ master ]
    branches: [ Cmake_deployment ]
  pull_request:
    branches: [ master ]
    branches: [ Cmake_deployment ]

jobs:
  Minimal_level:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make code
      
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
        
