name: Valgrind

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

   Valgrind_check :
    runs-on: ubuntu-latest
    steps :
      - uses: codecov/codecov-action@v1
      - uses : actions/checkout@v2
      - name : valgrind build
        run: |
          sudo apt-get install -y valgrind
          cd code 
          cd build
          cmake .. 
          cd ../../
          make code
          valgrind ./code/build/bin/project
      - name : valgrind test
        run: |
          sudo apt-get install -y valgrind
          cd code 
          cd build
          cmake .. 
          cd ../../
          make test
          valgrind ./code/build/bin/test
